version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
    networks:
      - app-network

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: personas
    ports:
      - "3306:3306"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
